import { db, ref, set, push, onValue, get, child, update, remove } from './firebaseConfig.js';

// DOM Elements
const itemForm = document.getElementById('itemForm');
const itemInput = document.getElementById('itemInput');
const itemsList = document.getElementById('itemsList');
const statusBadge = document.getElementById('statusBadge');

// Check if Firebase keys are configured
function checkConfigured() {
  // Simple UI warning check
  if (db.app.options.apiKey === "YOUR_API_KEY") {
    statusBadge.className = "status-warning";
    statusBadge.textContent = "⚠️ Add your Firebase config keys in firebaseConfig.js";
  } else {
    statusBadge.className = "status-online";
    statusBadge.textContent = "🟢 Connected to Firebase Realtime Database";
  }
}

// -------------------------------------------------------------
// 1. CREATE / PUSH DATA (Adding items to a list)
// -------------------------------------------------------------
itemForm.addEventListener('submit', (e) => {
  e.preventDefault();
  const title = itemInput.value.trim();
  if (!title) return;

  // Reference to the 'messages' node in Realtime DB
  const messagesRef = ref(db, 'messages');
  
  // Push generates a unique auto-ID key (e.g., -Nxyz123...)
  const newMsgRef = push(messagesRef);
  
  set(newMsgRef, {
    title: title,
    createdAt: Date.now()
  }).then(() => {
    itemInput.value = '';
    console.log('Item saved successfully!');
  }).catch((error) => {
    console.error('Error writing data:', error);
    alert('Firebase Error: ' + error.message);
  });
});

// -------------------------------------------------------------
// 2. READ REALTIME DATA (Live listener with onValue)
// -------------------------------------------------------------
function listenToMessages() {
  const messagesRef = ref(db, 'messages');

  // onValue listens for any live changes to 'messages'
  onValue(messagesRef, (snapshot) => {
    itemsList.innerHTML = '';
    const data = snapshot.val();

    if (!data) {
      itemsList.innerHTML = '<li class="empty-state">No items found. Add one above!</li>';
      return;
    }

    // Iterate through object keys (unique auto-IDs generated by push)
    Object.keys(data).forEach((id) => {
      const item = data[id];
      const li = document.createElement('li');
      li.className = 'item-card';

      const timeStr = new Date(item.createdAt).toLocaleTimeString();

      li.innerHTML = `
        <div class="item-info">
          <span class="item-title">${escapeHtml(item.title)}</span>
          <span class="item-time">${timeStr}</span>
        </div>
        <div class="item-actions">
          <button class="btn-edit" onclick="editItem('${id}', '${escapeHtml(item.title)}')">Edit</button>
          <button class="btn-delete" onclick="deleteItem('${id}')">Delete</button>
        </div>
      `;
      itemsList.appendChild(li);
    });
  }, (error) => {
    console.error("Database read error:", error);
  });
}

// -------------------------------------------------------------
// 3. UPDATE DATA (update specific fields)
// -------------------------------------------------------------
window.editItem = function(id, currentTitle) {
  const newTitle = prompt('Update item title:', currentTitle);
  if (newTitle === null || newTitle.trim() === '') return;

  const itemRef = ref(db, `messages/${id}`);
  update(itemRef, {
    title: newTitle.trim(),
    updatedAt: Date.now()
  }).then(() => {
    console.log('Item updated');
  }).catch((err) => {
    console.error('Update failed:', err);
  });
};

// -------------------------------------------------------------
// 4. DELETE DATA (remove node)
// -------------------------------------------------------------
window.deleteItem = function(id) {
  if (!confirm('Are you sure you want to delete this item?')) return;

  const itemRef = ref(db, `messages/${id}`);
  remove(itemRef).then(() => {
    console.log('Item removed');
  }).catch((err) => {
    console.error('Delete failed:', err);
  });
};

// Utility function to sanitize text
function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, (m) => {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[m];
  });
}

// Initialize on page load
checkConfigured();
listenToMessages();

// Optional Connection Test (runs on startup)

// 1. Test Writing to Firebase
set(ref(db, 'connection_test'), {
  status: "connected",
  timestamp: new Date().toLocaleTimeString()
})
.then(() => {
  console.log("✅ SUCCESS: Successfully written to Firebase!");
})
.catch((error) => {
  console.error("❌ ERROR: Connection failed:", error.message);
});

// 2. Test Reading from Firebase
onValue(ref(db, 'connection_test'), (snapshot) => {
  console.log("🟢 LIVE DATA FROM FIREBASE:", snapshot.val());
});